LFP/LFP/urls.py
from django.contrib import admin
from django.urls import path,include
from app1 import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    
    path('app1/',include('app1.urls')),
    path('logout/',views.user_logout,name='logout'),
    

]

LFP/app1/urls.py
from django.urls import path
from app1 import views

app_name="app1"

urlpatterns=[
    path('reg',views.register,name='register'),
    path('user_login',views.user_login,name='login'),
    
    
]

LFP/app1/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
    
    user=models.OneToOneField(User ,on_delete=callable)
    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(
        upload_to='profile_pics',
        blank=True
    )
    def __str__(self):
        return self.user.username

# Create your models here.

LFP/app1/forms.py
from django import forms
from django.contrib.auth.models import User
from app1.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')
        

LFP/app1/views.py
from django.shortcuts import render
from app1.forms import UserForm,UserProfileInfoForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout

def index(request):
    return render(request,'app1/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse('Logged in')
    

def register(request):
    registered=False
    if request.method=="POST":
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            profile=profile_form.save(commit=False)
            profile.user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILE['profile_pic']

            profile.save()
            registered=True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()
    return render(request,'app1/reg.html',
    {
        'user_form':user_form,
        'profile_form':profile_form,
        'registered':registered,
    })

def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Acoount is not active')
        else:
            print('Failed')
            return HttpResponse('Invalid')
    
    else:
        return render(request,'app1/login.html')


# Create your views here.

LFP/templates/app1/base.html
<body>
    <nav>
        <a href="{% url 'index' %}">Home</a>
        <a href="{% url 'app1:register' %}">Register</a>
        <a href="{% url 'admin:index' %}">Admin</a>
        {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Logout</a>
        {% else %}
        <a href="{% url 'app1:login' %}">Login</a>
        {% endif %}
    </nav>
    <div>
        {% block body_block %}
        {% endblock %}
    </div>
</body>

LFP/templates/app1/index.html
{% extends "app1/base.html" %}
{% block body_block %}
<div>
    <h1>django home page</h1>
</div>
{% endblock %}

LFP/templates/app1/login.html
{% extends 'app1/base.html' %}
{% block body_block %}
<h1>
    Login Please
</h1>
<form action="{% url 'app1:login' %}" method="POST">
{ % crsf_token % }
<label for="username">UserName</label>
<input type="text" name="username" id="">
<label for="password">Password</label>
<input type="text" name="password" id="">
<input type="submit" value="Login" id="">

</form>
{% endblock %}

LFP/templates/app1/reg.html
{% extends "app1/base.html" %}
{% block body_block %}

<div>
    {% if registered %}
         <h1>
        thankyou
        </h1>
    
    {% else %}
            <h1>
        Register here
        </h1>
        <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p}}
        {{profile_form.as_p}}
        
        <input type="submit" name="" id="" value="REGISTER">
        
        
        z </form>
    {% endif %} 
 
</div>
{% endblock %}